name = "nicobytes-store-api"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB_STORE"
database_name = "prod_nicobytes_store"
database_id = "0e2c1c39-db95-44de-8b24-41c82217b230"
preview_database_id="e6d426ae-1403-43cf-a2e8-2c7a48fda75f"
